/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountEditRouteImport } from './routes/account/edit'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerAuthedRouteImport } from './routes/customer/_authed'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as RiderAuthedRouteImport } from './routes/rider/_authed'
import { Route as AccountNotificationsIndexRouteImport } from './routes/account/notifications/index'
import { Route as AuthFindAccountIndexRouteImport } from './routes/auth/find-account/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthVerifyIndexRouteImport } from './routes/auth/verify/index'
import { Route as CustomerDeliveriesIndexRouteImport } from './routes/customer/deliveries/index'
import { Route as CustomerDeliveriesNewRouteImport } from './routes/customer/deliveries/new'
import { Route as CustomerLoginIndexRouteImport } from './routes/customer/login/index'
import { Route as CustomerPointsIndexRouteImport } from './routes/customer/points/index'
import { Route as CustomerPointsChargeRouteImport } from './routes/customer/points/charge'
import { Route as CustomerSignupIndexRouteImport } from './routes/customer/signup/index'
import { Route as RiderDeliveryIndexRouteImport } from './routes/rider/delivery/index'
import { Route as RiderHistoryIndexRouteImport } from './routes/rider/history/index'
import { Route as RiderLoginIndexRouteImport } from './routes/rider/login/index'
import { Route as RiderPointsIndexRouteImport } from './routes/rider/points/index'
import { Route as RiderRequestsIndexRouteImport } from './routes/rider/requests/index'
import { Route as RiderSignupIndexRouteImport } from './routes/rider/signup/index'
import { Route as CustomerDeliveriesDeliveryIdIndexRouteImport } from './routes/customer/deliveries/$deliveryId/index'
import { Route as CustomerDeliveriesDeliveryIdTrackingRouteImport } from './routes/customer/deliveries/$deliveryId/tracking'
import { Route as RiderHistoryDeliveryIdIndexRouteImport } from './routes/rider/history/$deliveryId/index'
import { Route as RiderRequestsDeliveryIdIndexRouteImport } from './routes/rider/requests/$deliveryId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEditRoute = AccountEditRouteImport.update({
  id: '/account/edit',
  path: '/account/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAuthedRoute = CustomerAuthedRouteImport.update({
  id: '/customer/_authed',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderAuthedRoute = RiderAuthedRouteImport.update({
  id: '/rider/_authed',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsIndexRoute =
  AccountNotificationsIndexRouteImport.update({
    id: '/account/notifications/',
    path: '/account/notifications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthFindAccountIndexRoute = AuthFindAccountIndexRouteImport.update({
  id: '/auth/find-account/',
  path: '/auth/find-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/auth/verify/',
  path: '/auth/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDeliveriesIndexRoute = CustomerDeliveriesIndexRouteImport.update({
  id: '/customer/deliveries/',
  path: '/customer/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDeliveriesNewRoute = CustomerDeliveriesNewRouteImport.update({
  id: '/customer/deliveries/new',
  path: '/customer/deliveries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginIndexRoute = CustomerLoginIndexRouteImport.update({
  id: '/customer/login/',
  path: '/customer/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPointsIndexRoute = CustomerPointsIndexRouteImport.update({
  id: '/customer/points/',
  path: '/customer/points/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPointsChargeRoute = CustomerPointsChargeRouteImport.update({
  id: '/customer/points/charge',
  path: '/customer/points/charge',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupIndexRoute = CustomerSignupIndexRouteImport.update({
  id: '/customer/signup/',
  path: '/customer/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderDeliveryIndexRoute = RiderDeliveryIndexRouteImport.update({
  id: '/rider/delivery/',
  path: '/rider/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderHistoryIndexRoute = RiderHistoryIndexRouteImport.update({
  id: '/rider/history/',
  path: '/rider/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderLoginIndexRoute = RiderLoginIndexRouteImport.update({
  id: '/rider/login/',
  path: '/rider/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderPointsIndexRoute = RiderPointsIndexRouteImport.update({
  id: '/rider/points/',
  path: '/rider/points/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRequestsIndexRoute = RiderRequestsIndexRouteImport.update({
  id: '/rider/requests/',
  path: '/rider/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSignupIndexRoute = RiderSignupIndexRouteImport.update({
  id: '/rider/signup/',
  path: '/rider/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDeliveriesDeliveryIdIndexRoute =
  CustomerDeliveriesDeliveryIdIndexRouteImport.update({
    id: '/customer/deliveries/$deliveryId/',
    path: '/customer/deliveries/$deliveryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDeliveriesDeliveryIdTrackingRoute =
  CustomerDeliveriesDeliveryIdTrackingRouteImport.update({
    id: '/customer/deliveries/$deliveryId/tracking',
    path: '/customer/deliveries/$deliveryId/tracking',
    getParentRoute: () => rootRouteImport,
  } as any)
const RiderHistoryDeliveryIdIndexRoute =
  RiderHistoryDeliveryIdIndexRouteImport.update({
    id: '/rider/history/$deliveryId/',
    path: '/rider/history/$deliveryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RiderRequestsDeliveryIdIndexRoute =
  RiderRequestsDeliveryIdIndexRouteImport.update({
    id: '/rider/requests/$deliveryId/',
    path: '/rider/requests/$deliveryId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/edit': typeof AccountEditRoute
  '/account/settings': typeof AccountSettingsRoute
  '/customer': typeof CustomerAuthedRoute
  '/rider': typeof RiderAuthedRoute
  '/account/': typeof AccountIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/customer/deliveries/new': typeof CustomerDeliveriesNewRoute
  '/customer/points/charge': typeof CustomerPointsChargeRoute
  '/account/notifications/': typeof AccountNotificationsIndexRoute
  '/auth/find-account/': typeof AuthFindAccountIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/customer/deliveries/': typeof CustomerDeliveriesIndexRoute
  '/customer/login/': typeof CustomerLoginIndexRoute
  '/customer/points/': typeof CustomerPointsIndexRoute
  '/customer/signup/': typeof CustomerSignupIndexRoute
  '/rider/delivery/': typeof RiderDeliveryIndexRoute
  '/rider/history/': typeof RiderHistoryIndexRoute
  '/rider/login/': typeof RiderLoginIndexRoute
  '/rider/points/': typeof RiderPointsIndexRoute
  '/rider/requests/': typeof RiderRequestsIndexRoute
  '/rider/signup/': typeof RiderSignupIndexRoute
  '/customer/deliveries/$deliveryId/tracking': typeof CustomerDeliveriesDeliveryIdTrackingRoute
  '/customer/deliveries/$deliveryId/': typeof CustomerDeliveriesDeliveryIdIndexRoute
  '/rider/history/$deliveryId/': typeof RiderHistoryDeliveryIdIndexRoute
  '/rider/requests/$deliveryId/': typeof RiderRequestsDeliveryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/edit': typeof AccountEditRoute
  '/account/settings': typeof AccountSettingsRoute
  '/customer': typeof CustomerIndexRoute
  '/rider': typeof RiderIndexRoute
  '/account': typeof AccountIndexRoute
  '/customer/deliveries/new': typeof CustomerDeliveriesNewRoute
  '/customer/points/charge': typeof CustomerPointsChargeRoute
  '/account/notifications': typeof AccountNotificationsIndexRoute
  '/auth/find-account': typeof AuthFindAccountIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/customer/deliveries': typeof CustomerDeliveriesIndexRoute
  '/customer/login': typeof CustomerLoginIndexRoute
  '/customer/points': typeof CustomerPointsIndexRoute
  '/customer/signup': typeof CustomerSignupIndexRoute
  '/rider/delivery': typeof RiderDeliveryIndexRoute
  '/rider/history': typeof RiderHistoryIndexRoute
  '/rider/login': typeof RiderLoginIndexRoute
  '/rider/points': typeof RiderPointsIndexRoute
  '/rider/requests': typeof RiderRequestsIndexRoute
  '/rider/signup': typeof RiderSignupIndexRoute
  '/customer/deliveries/$deliveryId/tracking': typeof CustomerDeliveriesDeliveryIdTrackingRoute
  '/customer/deliveries/$deliveryId': typeof CustomerDeliveriesDeliveryIdIndexRoute
  '/rider/history/$deliveryId': typeof RiderHistoryDeliveryIdIndexRoute
  '/rider/requests/$deliveryId': typeof RiderRequestsDeliveryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/edit': typeof AccountEditRoute
  '/account/settings': typeof AccountSettingsRoute
  '/customer/_authed': typeof CustomerAuthedRoute
  '/rider/_authed': typeof RiderAuthedRoute
  '/account/': typeof AccountIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/customer/deliveries/new': typeof CustomerDeliveriesNewRoute
  '/customer/points/charge': typeof CustomerPointsChargeRoute
  '/account/notifications/': typeof AccountNotificationsIndexRoute
  '/auth/find-account/': typeof AuthFindAccountIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/customer/deliveries/': typeof CustomerDeliveriesIndexRoute
  '/customer/login/': typeof CustomerLoginIndexRoute
  '/customer/points/': typeof CustomerPointsIndexRoute
  '/customer/signup/': typeof CustomerSignupIndexRoute
  '/rider/delivery/': typeof RiderDeliveryIndexRoute
  '/rider/history/': typeof RiderHistoryIndexRoute
  '/rider/login/': typeof RiderLoginIndexRoute
  '/rider/points/': typeof RiderPointsIndexRoute
  '/rider/requests/': typeof RiderRequestsIndexRoute
  '/rider/signup/': typeof RiderSignupIndexRoute
  '/customer/deliveries/$deliveryId/tracking': typeof CustomerDeliveriesDeliveryIdTrackingRoute
  '/customer/deliveries/$deliveryId/': typeof CustomerDeliveriesDeliveryIdIndexRoute
  '/rider/history/$deliveryId/': typeof RiderHistoryDeliveryIdIndexRoute
  '/rider/requests/$deliveryId/': typeof RiderRequestsDeliveryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/edit'
    | '/account/settings'
    | '/customer'
    | '/rider'
    | '/account/'
    | '/customer/'
    | '/rider/'
    | '/customer/deliveries/new'
    | '/customer/points/charge'
    | '/account/notifications/'
    | '/auth/find-account/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/customer/deliveries/'
    | '/customer/login/'
    | '/customer/points/'
    | '/customer/signup/'
    | '/rider/delivery/'
    | '/rider/history/'
    | '/rider/login/'
    | '/rider/points/'
    | '/rider/requests/'
    | '/rider/signup/'
    | '/customer/deliveries/$deliveryId/tracking'
    | '/customer/deliveries/$deliveryId/'
    | '/rider/history/$deliveryId/'
    | '/rider/requests/$deliveryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/edit'
    | '/account/settings'
    | '/customer'
    | '/rider'
    | '/account'
    | '/customer/deliveries/new'
    | '/customer/points/charge'
    | '/account/notifications'
    | '/auth/find-account'
    | '/auth/signup'
    | '/auth/verify'
    | '/customer/deliveries'
    | '/customer/login'
    | '/customer/points'
    | '/customer/signup'
    | '/rider/delivery'
    | '/rider/history'
    | '/rider/login'
    | '/rider/points'
    | '/rider/requests'
    | '/rider/signup'
    | '/customer/deliveries/$deliveryId/tracking'
    | '/customer/deliveries/$deliveryId'
    | '/rider/history/$deliveryId'
    | '/rider/requests/$deliveryId'
  id:
    | '__root__'
    | '/'
    | '/account/edit'
    | '/account/settings'
    | '/customer/_authed'
    | '/rider/_authed'
    | '/account/'
    | '/customer/'
    | '/rider/'
    | '/customer/deliveries/new'
    | '/customer/points/charge'
    | '/account/notifications/'
    | '/auth/find-account/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/customer/deliveries/'
    | '/customer/login/'
    | '/customer/points/'
    | '/customer/signup/'
    | '/rider/delivery/'
    | '/rider/history/'
    | '/rider/login/'
    | '/rider/points/'
    | '/rider/requests/'
    | '/rider/signup/'
    | '/customer/deliveries/$deliveryId/tracking'
    | '/customer/deliveries/$deliveryId/'
    | '/rider/history/$deliveryId/'
    | '/rider/requests/$deliveryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountEditRoute: typeof AccountEditRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  CustomerAuthedRoute: typeof CustomerAuthedRoute
  RiderAuthedRoute: typeof RiderAuthedRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
  CustomerDeliveriesNewRoute: typeof CustomerDeliveriesNewRoute
  CustomerPointsChargeRoute: typeof CustomerPointsChargeRoute
  AccountNotificationsIndexRoute: typeof AccountNotificationsIndexRoute
  AuthFindAccountIndexRoute: typeof AuthFindAccountIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
  CustomerDeliveriesIndexRoute: typeof CustomerDeliveriesIndexRoute
  CustomerLoginIndexRoute: typeof CustomerLoginIndexRoute
  CustomerPointsIndexRoute: typeof CustomerPointsIndexRoute
  CustomerSignupIndexRoute: typeof CustomerSignupIndexRoute
  RiderDeliveryIndexRoute: typeof RiderDeliveryIndexRoute
  RiderHistoryIndexRoute: typeof RiderHistoryIndexRoute
  RiderLoginIndexRoute: typeof RiderLoginIndexRoute
  RiderPointsIndexRoute: typeof RiderPointsIndexRoute
  RiderRequestsIndexRoute: typeof RiderRequestsIndexRoute
  RiderSignupIndexRoute: typeof RiderSignupIndexRoute
  CustomerDeliveriesDeliveryIdTrackingRoute: typeof CustomerDeliveriesDeliveryIdTrackingRoute
  CustomerDeliveriesDeliveryIdIndexRoute: typeof CustomerDeliveriesDeliveryIdIndexRoute
  RiderHistoryDeliveryIdIndexRoute: typeof RiderHistoryDeliveryIdIndexRoute
  RiderRequestsDeliveryIdIndexRoute: typeof RiderRequestsDeliveryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/edit': {
      id: '/account/edit'
      path: '/account/edit'
      fullPath: '/account/edit'
      preLoaderRoute: typeof AccountEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/_authed': {
      id: '/customer/_authed'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/_authed': {
      id: '/rider/_authed'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications/': {
      id: '/account/notifications/'
      path: '/account/notifications'
      fullPath: '/account/notifications/'
      preLoaderRoute: typeof AccountNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/find-account/': {
      id: '/auth/find-account/'
      path: '/auth/find-account'
      fullPath: '/auth/find-account/'
      preLoaderRoute: typeof AuthFindAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/auth/verify'
      fullPath: '/auth/verify/'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/deliveries/': {
      id: '/customer/deliveries/'
      path: '/customer/deliveries'
      fullPath: '/customer/deliveries/'
      preLoaderRoute: typeof CustomerDeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/deliveries/new': {
      id: '/customer/deliveries/new'
      path: '/customer/deliveries/new'
      fullPath: '/customer/deliveries/new'
      preLoaderRoute: typeof CustomerDeliveriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login/': {
      id: '/customer/login/'
      path: '/customer/login'
      fullPath: '/customer/login/'
      preLoaderRoute: typeof CustomerLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/points/': {
      id: '/customer/points/'
      path: '/customer/points'
      fullPath: '/customer/points/'
      preLoaderRoute: typeof CustomerPointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/points/charge': {
      id: '/customer/points/charge'
      path: '/customer/points/charge'
      fullPath: '/customer/points/charge'
      preLoaderRoute: typeof CustomerPointsChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup/': {
      id: '/customer/signup/'
      path: '/customer/signup'
      fullPath: '/customer/signup/'
      preLoaderRoute: typeof CustomerSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/delivery/': {
      id: '/rider/delivery/'
      path: '/rider/delivery'
      fullPath: '/rider/delivery/'
      preLoaderRoute: typeof RiderDeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/history/': {
      id: '/rider/history/'
      path: '/rider/history'
      fullPath: '/rider/history/'
      preLoaderRoute: typeof RiderHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/login/': {
      id: '/rider/login/'
      path: '/rider/login'
      fullPath: '/rider/login/'
      preLoaderRoute: typeof RiderLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/points/': {
      id: '/rider/points/'
      path: '/rider/points'
      fullPath: '/rider/points/'
      preLoaderRoute: typeof RiderPointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/requests/': {
      id: '/rider/requests/'
      path: '/rider/requests'
      fullPath: '/rider/requests/'
      preLoaderRoute: typeof RiderRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/signup/': {
      id: '/rider/signup/'
      path: '/rider/signup'
      fullPath: '/rider/signup/'
      preLoaderRoute: typeof RiderSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/deliveries/$deliveryId/': {
      id: '/customer/deliveries/$deliveryId/'
      path: '/customer/deliveries/$deliveryId'
      fullPath: '/customer/deliveries/$deliveryId/'
      preLoaderRoute: typeof CustomerDeliveriesDeliveryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/deliveries/$deliveryId/tracking': {
      id: '/customer/deliveries/$deliveryId/tracking'
      path: '/customer/deliveries/$deliveryId/tracking'
      fullPath: '/customer/deliveries/$deliveryId/tracking'
      preLoaderRoute: typeof CustomerDeliveriesDeliveryIdTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/history/$deliveryId/': {
      id: '/rider/history/$deliveryId/'
      path: '/rider/history/$deliveryId'
      fullPath: '/rider/history/$deliveryId/'
      preLoaderRoute: typeof RiderHistoryDeliveryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/requests/$deliveryId/': {
      id: '/rider/requests/$deliveryId/'
      path: '/rider/requests/$deliveryId'
      fullPath: '/rider/requests/$deliveryId/'
      preLoaderRoute: typeof RiderRequestsDeliveryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountEditRoute: AccountEditRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  CustomerAuthedRoute: CustomerAuthedRoute,
  RiderAuthedRoute: RiderAuthedRoute,
  AccountIndexRoute: AccountIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
  CustomerDeliveriesNewRoute: CustomerDeliveriesNewRoute,
  CustomerPointsChargeRoute: CustomerPointsChargeRoute,
  AccountNotificationsIndexRoute: AccountNotificationsIndexRoute,
  AuthFindAccountIndexRoute: AuthFindAccountIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
  CustomerDeliveriesIndexRoute: CustomerDeliveriesIndexRoute,
  CustomerLoginIndexRoute: CustomerLoginIndexRoute,
  CustomerPointsIndexRoute: CustomerPointsIndexRoute,
  CustomerSignupIndexRoute: CustomerSignupIndexRoute,
  RiderDeliveryIndexRoute: RiderDeliveryIndexRoute,
  RiderHistoryIndexRoute: RiderHistoryIndexRoute,
  RiderLoginIndexRoute: RiderLoginIndexRoute,
  RiderPointsIndexRoute: RiderPointsIndexRoute,
  RiderRequestsIndexRoute: RiderRequestsIndexRoute,
  RiderSignupIndexRoute: RiderSignupIndexRoute,
  CustomerDeliveriesDeliveryIdTrackingRoute:
    CustomerDeliveriesDeliveryIdTrackingRoute,
  CustomerDeliveriesDeliveryIdIndexRoute:
    CustomerDeliveriesDeliveryIdIndexRoute,
  RiderHistoryDeliveryIdIndexRoute: RiderHistoryDeliveryIdIndexRoute,
  RiderRequestsDeliveryIdIndexRoute: RiderRequestsDeliveryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
