/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountEditRouteImport } from './routes/account/edit'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as CustomerAuthedRouteImport } from './routes/customer/_authed'
import { Route as RiderAuthedRouteImport } from './routes/rider/_authed'
import { Route as AccountNotificationsIndexRouteImport } from './routes/account/notifications/index'
import { Route as AuthFindAccountIndexRouteImport } from './routes/auth/find-account/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthVerifyIndexRouteImport } from './routes/auth/verify/index'
import { Route as CustomerAuthedIndexRouteImport } from './routes/customer/_authed/index'
import { Route as CustomerLoginIndexRouteImport } from './routes/customer/login/index'
import { Route as CustomerSignupIndexRouteImport } from './routes/customer/signup/index'
import { Route as RiderAuthedIndexRouteImport } from './routes/rider/_authed/index'
import { Route as RiderLoginIndexRouteImport } from './routes/rider/login/index'
import { Route as RiderSignupIndexRouteImport } from './routes/rider/signup/index'
import { Route as CustomerAuthedDeliveriesIndexRouteImport } from './routes/customer/_authed/deliveries/index'
import { Route as CustomerAuthedDeliveriesNewRouteImport } from './routes/customer/_authed/deliveries/new'
import { Route as CustomerAuthedPointsIndexRouteImport } from './routes/customer/_authed/points/index'
import { Route as CustomerAuthedPointsChargeRouteImport } from './routes/customer/_authed/points/charge'
import { Route as RiderAuthedDeliveryIndexRouteImport } from './routes/rider/_authed/delivery/index'
import { Route as RiderAuthedHistoryIndexRouteImport } from './routes/rider/_authed/history/index'
import { Route as RiderAuthedPointsIndexRouteImport } from './routes/rider/_authed/points/index'
import { Route as RiderAuthedRequestsIndexRouteImport } from './routes/rider/_authed/requests/index'
import { Route as CustomerAuthedDeliveriesDeliveryIdIndexRouteImport } from './routes/customer/_authed/deliveries/$deliveryId/index'
import { Route as CustomerAuthedDeliveriesDeliveryIdTrackingRouteImport } from './routes/customer/_authed/deliveries/$deliveryId/tracking'
import { Route as RiderAuthedDeliveryDeliveryIdCompleteRouteImport } from './routes/rider/_authed/delivery/$deliveryId/complete'
import { Route as RiderAuthedHistoryDeliveryIdIndexRouteImport } from './routes/rider/_authed/history/$deliveryId/index'
import { Route as RiderAuthedRequestsDeliveryIdIndexRouteImport } from './routes/rider/_authed/requests/$deliveryId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountEditRoute = AccountEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CustomerAuthedRoute = CustomerAuthedRouteImport.update({
  id: '/customer/_authed',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderAuthedRoute = RiderAuthedRouteImport.update({
  id: '/rider/_authed',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsIndexRoute =
  AccountNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AccountRouteRoute,
  } as any)
const AuthFindAccountIndexRoute = AuthFindAccountIndexRouteImport.update({
  id: '/find-account/',
  path: '/find-account/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const CustomerAuthedIndexRoute = CustomerAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerAuthedRoute,
} as any)
const CustomerLoginIndexRoute = CustomerLoginIndexRouteImport.update({
  id: '/customer/login/',
  path: '/customer/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSignupIndexRoute = CustomerSignupIndexRouteImport.update({
  id: '/customer/signup/',
  path: '/customer/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderAuthedIndexRoute = RiderAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiderAuthedRoute,
} as any)
const RiderLoginIndexRoute = RiderLoginIndexRouteImport.update({
  id: '/rider/login/',
  path: '/rider/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSignupIndexRoute = RiderSignupIndexRouteImport.update({
  id: '/rider/signup/',
  path: '/rider/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAuthedDeliveriesIndexRoute =
  CustomerAuthedDeliveriesIndexRouteImport.update({
    id: '/deliveries/',
    path: '/deliveries/',
    getParentRoute: () => CustomerAuthedRoute,
  } as any)
const CustomerAuthedDeliveriesNewRoute =
  CustomerAuthedDeliveriesNewRouteImport.update({
    id: '/deliveries/new',
    path: '/deliveries/new',
    getParentRoute: () => CustomerAuthedRoute,
  } as any)
const CustomerAuthedPointsIndexRoute =
  CustomerAuthedPointsIndexRouteImport.update({
    id: '/points/',
    path: '/points/',
    getParentRoute: () => CustomerAuthedRoute,
  } as any)
const CustomerAuthedPointsChargeRoute =
  CustomerAuthedPointsChargeRouteImport.update({
    id: '/points/charge',
    path: '/points/charge',
    getParentRoute: () => CustomerAuthedRoute,
  } as any)
const RiderAuthedDeliveryIndexRoute =
  RiderAuthedDeliveryIndexRouteImport.update({
    id: '/delivery/',
    path: '/delivery/',
    getParentRoute: () => RiderAuthedRoute,
  } as any)
const RiderAuthedHistoryIndexRoute = RiderAuthedHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => RiderAuthedRoute,
} as any)
const RiderAuthedPointsIndexRoute = RiderAuthedPointsIndexRouteImport.update({
  id: '/points/',
  path: '/points/',
  getParentRoute: () => RiderAuthedRoute,
} as any)
const RiderAuthedRequestsIndexRoute =
  RiderAuthedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => RiderAuthedRoute,
  } as any)
const CustomerAuthedDeliveriesDeliveryIdIndexRoute =
  CustomerAuthedDeliveriesDeliveryIdIndexRouteImport.update({
    id: '/deliveries/$deliveryId/',
    path: '/deliveries/$deliveryId/',
    getParentRoute: () => CustomerAuthedRoute,
  } as any)
const CustomerAuthedDeliveriesDeliveryIdTrackingRoute =
  CustomerAuthedDeliveriesDeliveryIdTrackingRouteImport.update({
    id: '/deliveries/$deliveryId/tracking',
    path: '/deliveries/$deliveryId/tracking',
    getParentRoute: () => CustomerAuthedRoute,
  } as any)
const RiderAuthedDeliveryDeliveryIdCompleteRoute =
  RiderAuthedDeliveryDeliveryIdCompleteRouteImport.update({
    id: '/delivery/$deliveryId/complete',
    path: '/delivery/$deliveryId/complete',
    getParentRoute: () => RiderAuthedRoute,
  } as any)
const RiderAuthedHistoryDeliveryIdIndexRoute =
  RiderAuthedHistoryDeliveryIdIndexRouteImport.update({
    id: '/history/$deliveryId/',
    path: '/history/$deliveryId/',
    getParentRoute: () => RiderAuthedRoute,
  } as any)
const RiderAuthedRequestsDeliveryIdIndexRoute =
  RiderAuthedRequestsDeliveryIdIndexRouteImport.update({
    id: '/requests/$deliveryId/',
    path: '/requests/$deliveryId/',
    getParentRoute: () => RiderAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/account/edit': typeof AccountEditRoute
  '/account/settings': typeof AccountSettingsRoute
  '/customer': typeof CustomerAuthedRouteWithChildren
  '/rider': typeof RiderAuthedRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/account/notifications/': typeof AccountNotificationsIndexRoute
  '/auth/find-account/': typeof AuthFindAccountIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/customer/': typeof CustomerAuthedIndexRoute
  '/customer/login/': typeof CustomerLoginIndexRoute
  '/customer/signup/': typeof CustomerSignupIndexRoute
  '/rider/': typeof RiderAuthedIndexRoute
  '/rider/login/': typeof RiderLoginIndexRoute
  '/rider/signup/': typeof RiderSignupIndexRoute
  '/customer/deliveries/new': typeof CustomerAuthedDeliveriesNewRoute
  '/customer/points/charge': typeof CustomerAuthedPointsChargeRoute
  '/customer/deliveries/': typeof CustomerAuthedDeliveriesIndexRoute
  '/customer/points/': typeof CustomerAuthedPointsIndexRoute
  '/rider/delivery/': typeof RiderAuthedDeliveryIndexRoute
  '/rider/history/': typeof RiderAuthedHistoryIndexRoute
  '/rider/points/': typeof RiderAuthedPointsIndexRoute
  '/rider/requests/': typeof RiderAuthedRequestsIndexRoute
  '/customer/deliveries/$deliveryId/tracking': typeof CustomerAuthedDeliveriesDeliveryIdTrackingRoute
  '/rider/delivery/$deliveryId/complete': typeof RiderAuthedDeliveryDeliveryIdCompleteRoute
  '/customer/deliveries/$deliveryId/': typeof CustomerAuthedDeliveriesDeliveryIdIndexRoute
  '/rider/history/$deliveryId/': typeof RiderAuthedHistoryDeliveryIdIndexRoute
  '/rider/requests/$deliveryId/': typeof RiderAuthedRequestsDeliveryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/account/edit': typeof AccountEditRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account': typeof AccountIndexRoute
  '/account/notifications': typeof AccountNotificationsIndexRoute
  '/auth/find-account': typeof AuthFindAccountIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/customer': typeof CustomerAuthedIndexRoute
  '/customer/login': typeof CustomerLoginIndexRoute
  '/customer/signup': typeof CustomerSignupIndexRoute
  '/rider': typeof RiderAuthedIndexRoute
  '/rider/login': typeof RiderLoginIndexRoute
  '/rider/signup': typeof RiderSignupIndexRoute
  '/customer/deliveries/new': typeof CustomerAuthedDeliveriesNewRoute
  '/customer/points/charge': typeof CustomerAuthedPointsChargeRoute
  '/customer/deliveries': typeof CustomerAuthedDeliveriesIndexRoute
  '/customer/points': typeof CustomerAuthedPointsIndexRoute
  '/rider/delivery': typeof RiderAuthedDeliveryIndexRoute
  '/rider/history': typeof RiderAuthedHistoryIndexRoute
  '/rider/points': typeof RiderAuthedPointsIndexRoute
  '/rider/requests': typeof RiderAuthedRequestsIndexRoute
  '/customer/deliveries/$deliveryId/tracking': typeof CustomerAuthedDeliveriesDeliveryIdTrackingRoute
  '/rider/delivery/$deliveryId/complete': typeof RiderAuthedDeliveryDeliveryIdCompleteRoute
  '/customer/deliveries/$deliveryId': typeof CustomerAuthedDeliveriesDeliveryIdIndexRoute
  '/rider/history/$deliveryId': typeof RiderAuthedHistoryDeliveryIdIndexRoute
  '/rider/requests/$deliveryId': typeof RiderAuthedRequestsDeliveryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/account/edit': typeof AccountEditRoute
  '/account/settings': typeof AccountSettingsRoute
  '/customer/_authed': typeof CustomerAuthedRouteWithChildren
  '/rider/_authed': typeof RiderAuthedRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/account/notifications/': typeof AccountNotificationsIndexRoute
  '/auth/find-account/': typeof AuthFindAccountIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/customer/_authed/': typeof CustomerAuthedIndexRoute
  '/customer/login/': typeof CustomerLoginIndexRoute
  '/customer/signup/': typeof CustomerSignupIndexRoute
  '/rider/_authed/': typeof RiderAuthedIndexRoute
  '/rider/login/': typeof RiderLoginIndexRoute
  '/rider/signup/': typeof RiderSignupIndexRoute
  '/customer/_authed/deliveries/new': typeof CustomerAuthedDeliveriesNewRoute
  '/customer/_authed/points/charge': typeof CustomerAuthedPointsChargeRoute
  '/customer/_authed/deliveries/': typeof CustomerAuthedDeliveriesIndexRoute
  '/customer/_authed/points/': typeof CustomerAuthedPointsIndexRoute
  '/rider/_authed/delivery/': typeof RiderAuthedDeliveryIndexRoute
  '/rider/_authed/history/': typeof RiderAuthedHistoryIndexRoute
  '/rider/_authed/points/': typeof RiderAuthedPointsIndexRoute
  '/rider/_authed/requests/': typeof RiderAuthedRequestsIndexRoute
  '/customer/_authed/deliveries/$deliveryId/tracking': typeof CustomerAuthedDeliveriesDeliveryIdTrackingRoute
  '/rider/_authed/delivery/$deliveryId/complete': typeof RiderAuthedDeliveryDeliveryIdCompleteRoute
  '/customer/_authed/deliveries/$deliveryId/': typeof CustomerAuthedDeliveriesDeliveryIdIndexRoute
  '/rider/_authed/history/$deliveryId/': typeof RiderAuthedHistoryDeliveryIdIndexRoute
  '/rider/_authed/requests/$deliveryId/': typeof RiderAuthedRequestsDeliveryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/account/edit'
    | '/account/settings'
    | '/customer'
    | '/rider'
    | '/account/'
    | '/account/notifications/'
    | '/auth/find-account/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/customer/'
    | '/customer/login/'
    | '/customer/signup/'
    | '/rider/'
    | '/rider/login/'
    | '/rider/signup/'
    | '/customer/deliveries/new'
    | '/customer/points/charge'
    | '/customer/deliveries/'
    | '/customer/points/'
    | '/rider/delivery/'
    | '/rider/history/'
    | '/rider/points/'
    | '/rider/requests/'
    | '/customer/deliveries/$deliveryId/tracking'
    | '/rider/delivery/$deliveryId/complete'
    | '/customer/deliveries/$deliveryId/'
    | '/rider/history/$deliveryId/'
    | '/rider/requests/$deliveryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account/edit'
    | '/account/settings'
    | '/account'
    | '/account/notifications'
    | '/auth/find-account'
    | '/auth/signup'
    | '/auth/verify'
    | '/customer'
    | '/customer/login'
    | '/customer/signup'
    | '/rider'
    | '/rider/login'
    | '/rider/signup'
    | '/customer/deliveries/new'
    | '/customer/points/charge'
    | '/customer/deliveries'
    | '/customer/points'
    | '/rider/delivery'
    | '/rider/history'
    | '/rider/points'
    | '/rider/requests'
    | '/customer/deliveries/$deliveryId/tracking'
    | '/rider/delivery/$deliveryId/complete'
    | '/customer/deliveries/$deliveryId'
    | '/rider/history/$deliveryId'
    | '/rider/requests/$deliveryId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/account/edit'
    | '/account/settings'
    | '/customer/_authed'
    | '/rider/_authed'
    | '/account/'
    | '/account/notifications/'
    | '/auth/find-account/'
    | '/auth/signup/'
    | '/auth/verify/'
    | '/customer/_authed/'
    | '/customer/login/'
    | '/customer/signup/'
    | '/rider/_authed/'
    | '/rider/login/'
    | '/rider/signup/'
    | '/customer/_authed/deliveries/new'
    | '/customer/_authed/points/charge'
    | '/customer/_authed/deliveries/'
    | '/customer/_authed/points/'
    | '/rider/_authed/delivery/'
    | '/rider/_authed/history/'
    | '/rider/_authed/points/'
    | '/rider/_authed/requests/'
    | '/customer/_authed/deliveries/$deliveryId/tracking'
    | '/rider/_authed/delivery/$deliveryId/complete'
    | '/customer/_authed/deliveries/$deliveryId/'
    | '/rider/_authed/history/$deliveryId/'
    | '/rider/_authed/requests/$deliveryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CustomerAuthedRoute: typeof CustomerAuthedRouteWithChildren
  RiderAuthedRoute: typeof RiderAuthedRouteWithChildren
  CustomerLoginIndexRoute: typeof CustomerLoginIndexRoute
  CustomerSignupIndexRoute: typeof CustomerSignupIndexRoute
  RiderLoginIndexRoute: typeof RiderLoginIndexRoute
  RiderSignupIndexRoute: typeof RiderSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/edit': {
      id: '/account/edit'
      path: '/edit'
      fullPath: '/account/edit'
      preLoaderRoute: typeof AccountEditRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/customer/_authed': {
      id: '/customer/_authed'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/_authed': {
      id: '/rider/_authed'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications/': {
      id: '/account/notifications/'
      path: '/notifications'
      fullPath: '/account/notifications/'
      preLoaderRoute: typeof AccountNotificationsIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/auth/find-account/': {
      id: '/auth/find-account/'
      path: '/find-account'
      fullPath: '/auth/find-account/'
      preLoaderRoute: typeof AuthFindAccountIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/verify'
      fullPath: '/auth/verify/'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/customer/_authed/': {
      id: '/customer/_authed/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerAuthedIndexRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/customer/login/': {
      id: '/customer/login/'
      path: '/customer/login'
      fullPath: '/customer/login/'
      preLoaderRoute: typeof CustomerLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/signup/': {
      id: '/customer/signup/'
      path: '/customer/signup'
      fullPath: '/customer/signup/'
      preLoaderRoute: typeof CustomerSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/_authed/': {
      id: '/rider/_authed/'
      path: '/'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderAuthedIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/rider/login/': {
      id: '/rider/login/'
      path: '/rider/login'
      fullPath: '/rider/login/'
      preLoaderRoute: typeof RiderLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/signup/': {
      id: '/rider/signup/'
      path: '/rider/signup'
      fullPath: '/rider/signup/'
      preLoaderRoute: typeof RiderSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/_authed/deliveries/': {
      id: '/customer/_authed/deliveries/'
      path: '/deliveries'
      fullPath: '/customer/deliveries/'
      preLoaderRoute: typeof CustomerAuthedDeliveriesIndexRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/customer/_authed/deliveries/new': {
      id: '/customer/_authed/deliveries/new'
      path: '/deliveries/new'
      fullPath: '/customer/deliveries/new'
      preLoaderRoute: typeof CustomerAuthedDeliveriesNewRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/customer/_authed/points/': {
      id: '/customer/_authed/points/'
      path: '/points'
      fullPath: '/customer/points/'
      preLoaderRoute: typeof CustomerAuthedPointsIndexRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/customer/_authed/points/charge': {
      id: '/customer/_authed/points/charge'
      path: '/points/charge'
      fullPath: '/customer/points/charge'
      preLoaderRoute: typeof CustomerAuthedPointsChargeRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/rider/_authed/delivery/': {
      id: '/rider/_authed/delivery/'
      path: '/delivery'
      fullPath: '/rider/delivery/'
      preLoaderRoute: typeof RiderAuthedDeliveryIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/rider/_authed/history/': {
      id: '/rider/_authed/history/'
      path: '/history'
      fullPath: '/rider/history/'
      preLoaderRoute: typeof RiderAuthedHistoryIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/rider/_authed/points/': {
      id: '/rider/_authed/points/'
      path: '/points'
      fullPath: '/rider/points/'
      preLoaderRoute: typeof RiderAuthedPointsIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/rider/_authed/requests/': {
      id: '/rider/_authed/requests/'
      path: '/requests'
      fullPath: '/rider/requests/'
      preLoaderRoute: typeof RiderAuthedRequestsIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/customer/_authed/deliveries/$deliveryId/': {
      id: '/customer/_authed/deliveries/$deliveryId/'
      path: '/deliveries/$deliveryId'
      fullPath: '/customer/deliveries/$deliveryId/'
      preLoaderRoute: typeof CustomerAuthedDeliveriesDeliveryIdIndexRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/customer/_authed/deliveries/$deliveryId/tracking': {
      id: '/customer/_authed/deliveries/$deliveryId/tracking'
      path: '/deliveries/$deliveryId/tracking'
      fullPath: '/customer/deliveries/$deliveryId/tracking'
      preLoaderRoute: typeof CustomerAuthedDeliveriesDeliveryIdTrackingRouteImport
      parentRoute: typeof CustomerAuthedRoute
    }
    '/rider/_authed/delivery/$deliveryId/complete': {
      id: '/rider/_authed/delivery/$deliveryId/complete'
      path: '/delivery/$deliveryId/complete'
      fullPath: '/rider/delivery/$deliveryId/complete'
      preLoaderRoute: typeof RiderAuthedDeliveryDeliveryIdCompleteRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/rider/_authed/history/$deliveryId/': {
      id: '/rider/_authed/history/$deliveryId/'
      path: '/history/$deliveryId'
      fullPath: '/rider/history/$deliveryId/'
      preLoaderRoute: typeof RiderAuthedHistoryDeliveryIdIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
    '/rider/_authed/requests/$deliveryId/': {
      id: '/rider/_authed/requests/$deliveryId/'
      path: '/requests/$deliveryId'
      fullPath: '/rider/requests/$deliveryId/'
      preLoaderRoute: typeof RiderAuthedRequestsDeliveryIdIndexRouteImport
      parentRoute: typeof RiderAuthedRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountEditRoute: typeof AccountEditRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountNotificationsIndexRoute: typeof AccountNotificationsIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountEditRoute: AccountEditRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountNotificationsIndexRoute: AccountNotificationsIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthFindAccountIndexRoute: typeof AuthFindAccountIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthFindAccountIndexRoute: AuthFindAccountIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CustomerAuthedRouteChildren {
  CustomerAuthedIndexRoute: typeof CustomerAuthedIndexRoute
  CustomerAuthedDeliveriesNewRoute: typeof CustomerAuthedDeliveriesNewRoute
  CustomerAuthedPointsChargeRoute: typeof CustomerAuthedPointsChargeRoute
  CustomerAuthedDeliveriesIndexRoute: typeof CustomerAuthedDeliveriesIndexRoute
  CustomerAuthedPointsIndexRoute: typeof CustomerAuthedPointsIndexRoute
  CustomerAuthedDeliveriesDeliveryIdTrackingRoute: typeof CustomerAuthedDeliveriesDeliveryIdTrackingRoute
  CustomerAuthedDeliveriesDeliveryIdIndexRoute: typeof CustomerAuthedDeliveriesDeliveryIdIndexRoute
}

const CustomerAuthedRouteChildren: CustomerAuthedRouteChildren = {
  CustomerAuthedIndexRoute: CustomerAuthedIndexRoute,
  CustomerAuthedDeliveriesNewRoute: CustomerAuthedDeliveriesNewRoute,
  CustomerAuthedPointsChargeRoute: CustomerAuthedPointsChargeRoute,
  CustomerAuthedDeliveriesIndexRoute: CustomerAuthedDeliveriesIndexRoute,
  CustomerAuthedPointsIndexRoute: CustomerAuthedPointsIndexRoute,
  CustomerAuthedDeliveriesDeliveryIdTrackingRoute:
    CustomerAuthedDeliveriesDeliveryIdTrackingRoute,
  CustomerAuthedDeliveriesDeliveryIdIndexRoute:
    CustomerAuthedDeliveriesDeliveryIdIndexRoute,
}

const CustomerAuthedRouteWithChildren = CustomerAuthedRoute._addFileChildren(
  CustomerAuthedRouteChildren,
)

interface RiderAuthedRouteChildren {
  RiderAuthedIndexRoute: typeof RiderAuthedIndexRoute
  RiderAuthedDeliveryIndexRoute: typeof RiderAuthedDeliveryIndexRoute
  RiderAuthedHistoryIndexRoute: typeof RiderAuthedHistoryIndexRoute
  RiderAuthedPointsIndexRoute: typeof RiderAuthedPointsIndexRoute
  RiderAuthedRequestsIndexRoute: typeof RiderAuthedRequestsIndexRoute
  RiderAuthedDeliveryDeliveryIdCompleteRoute: typeof RiderAuthedDeliveryDeliveryIdCompleteRoute
  RiderAuthedHistoryDeliveryIdIndexRoute: typeof RiderAuthedHistoryDeliveryIdIndexRoute
  RiderAuthedRequestsDeliveryIdIndexRoute: typeof RiderAuthedRequestsDeliveryIdIndexRoute
}

const RiderAuthedRouteChildren: RiderAuthedRouteChildren = {
  RiderAuthedIndexRoute: RiderAuthedIndexRoute,
  RiderAuthedDeliveryIndexRoute: RiderAuthedDeliveryIndexRoute,
  RiderAuthedHistoryIndexRoute: RiderAuthedHistoryIndexRoute,
  RiderAuthedPointsIndexRoute: RiderAuthedPointsIndexRoute,
  RiderAuthedRequestsIndexRoute: RiderAuthedRequestsIndexRoute,
  RiderAuthedDeliveryDeliveryIdCompleteRoute:
    RiderAuthedDeliveryDeliveryIdCompleteRoute,
  RiderAuthedHistoryDeliveryIdIndexRoute:
    RiderAuthedHistoryDeliveryIdIndexRoute,
  RiderAuthedRequestsDeliveryIdIndexRoute:
    RiderAuthedRequestsDeliveryIdIndexRoute,
}

const RiderAuthedRouteWithChildren = RiderAuthedRoute._addFileChildren(
  RiderAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CustomerAuthedRoute: CustomerAuthedRouteWithChildren,
  RiderAuthedRoute: RiderAuthedRouteWithChildren,
  CustomerLoginIndexRoute: CustomerLoginIndexRoute,
  CustomerSignupIndexRoute: CustomerSignupIndexRoute,
  RiderLoginIndexRoute: RiderLoginIndexRoute,
  RiderSignupIndexRoute: RiderSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
